name: SIPERA Test

on:
  push:
    branches:
      - main
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependency
        working-directory: backend
        run: npm install

      - name: Run Test
        working-directory: backend
        run: npm test